sim_names = """
alpha-decay_en
balloons-and-buoyancy_en
band-structure_en
battery-resistor-circuit_en
battery-voltage_en
beta-decay_en
bound-states_en
build-a-molecule_en
capacitor-lab_en
circuit-construction-kit-ac_en
circuit-construction-kit-ac-virtual-lab_en
conductivity_en
covalent-bonds_en
davisson-germer_en
discharge-lamps_en
eating-and-exercise_en
efield_en
electric-hockey_en
energy-skate-park_en
faraday_en
fluid-pressure-and-flow_en
forces-1d_en
forces-and-motion_en
fourier_en
gene-machine-lac-operon_en
generator_en
glaciers_en
greenhouse_en
hydrogen-atom_en
ladybug-motion-2d_en
lasers_en
list.txt
magnet-and-compass_en
magnets-and-electromagnets_en
maze-game_en
membrane-channels_en
microwaves_en
molecular-motors_en
motion-2d_en
moving-man_en
mri_en
natural-selection_en
nuclear-fission_en
optical-quantum-control_en
optical-tweezers_en
photoelectric_en
plate-tectonics_en
quantum-tunneling_en
quantum-wave-interference_en
radioactive-dating-game_en
radio-waves_en
ramp-forces-and-motion_en
reactions-and-rates_en
reversible-reactions_en
rotation_en
self-driven-particle-model_en
semiconductor_en
signal-circuit_en
soluble-salts_en
sound_en
stretching-dna_en
sugar-and-salt-solutions_en
the-ramp_en
torque_en
""".strip().split("\n")